version: '3.4'

services:
  mobileapp:
    image: mobileapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8792:8792


